wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.16
    start_time: 1679293601.556731
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.7.16
      5: 0.14.0
      8:
      - 5
architecture:
  desc: null
  value: xresnet50
dataset:
  desc: null
  value: imagenet-1k
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.001
